name: nexus-shell

services:
  db-postgres:
    image: postgres:16-alpine
    container_name: nexus-shell_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: nexus-shell_pgadmin
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker_data/pgadmin:/var/lib/pgadmin
    ports:
      - "8033:80"
    depends_on:
      - db-postgres

  db-redis:
    image: redis:7.2-alpine
    container_name: nexus-shell_redis
    restart: always
    command:
      - redis-server
      - --requirepass
      - "${REDIS__PASSWORD}"
      - --user
      - "${REDIS__USERNAME}"
      - "on"
      - ">${REDIS__PASSWORD}"
      - "~${KEY_BUILDER__PREFIX}:*"
      - "+@read"
      - "+@write"
      - "+@connection"
      - "+auth"
      - "-@admin"
      - "-@dangerous"
      - "-select"
    volumes:
      - ./docker_data/redis:/data
    ports:
      - "${REDIS__PORT}:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: nexus-shell_redisinsight
    restart: always
    environment:
      - RI_APP_PORT=5540
    volumes:
      - ./docker_data/redisinsight:/data
    ports:
      - "5541:5540"
    depends_on:
      - db-redis

#  redis-commander:
#      image: rediscommander/redis-commander:latest
#      container_name: nexus-shell_redis_commander
#      restart: always
#      environment:
#        - REDIS_HOSTS=local:db-redis:6379:0:${REDIS__PASSWORD}:${REDIS__USERNAME}
#      ports:
#        - "8082:8081"
#      depends_on:
#        - db-redis